### ISSUE TITLE
only Fan Speed can be seen on Dell Power Edge R720

### ISSUE THREAD

**Issue by jkl8808** [Breina/idrac_power_monitor#15]
<img width="700" alt="image" src="https://github.com/Breina/idrac_power_monitor/assets/140929290/fff96739-5822-421b-83b3-70a53784c863">
“未知”means unknown

**Comment by Breina** [comment]
Just to confirm, did you wait a couple of minutes? Updates aren't immediately and are scheduled by the update interval (defaults to 5 minutes).
Please share your logs, HA version and `idrac_power_monitor` version, so that I can check what's going on.

**Comment by Breina** [comment]
Should be fixed. Please test v1.2.6 and report back.
