### ISSUE TITLE
entity state unknown after update HA 20024.5.0 

### ISSUE THREAD

**Issue by pbvdven** [Breina/idrac_power_monitor#16]
After update of ha core to 2024.5.0 the entitys of the idrac intergration become unknown 

error :

Detected that custom integration 'idrac_power' calls async_write_ha_state from a thread at custom_components/idrac_power/sensor.py, line 130: self.async_schedule_update_ha_state(), please report it to the author of the 'idrac_power' custom integration
Detected that custom integration 'idrac_power' calls async_write_ha_state from a thread at custom_components/idrac_power/binary_sensor.py, line 79: self.async_schedule_update_ha_state(), please report it to the author of the 'idrac_power' custom integration

**Comment by Breina** [comment]
Should be fixed. Please test v1.2.6 and report back.
