### ISSUE TITLE
LOGIN issues

### ISSUE THREAD

**Issue by cmar7945** [Breina/idrac_power_monitor#26]
So I have this installed on my HA instance, but iDrac connection fails every time. HA states Cannot connect, but the login is noted in iDRAC logs, but HA keeps refusing to connect to the idrac redfish interface despite being enabled

**Comment by Breina** [comment]
Please confirm it's working manually:

`curl --location --request GET 'https://SERVER_IP/redfish/v1/Chassis/System.Embedded.1' \
--header 'Authorization: Basic TOKEN`

Where token is the base64 of `USERNAME:PASSWORD`, or for convenience: https://www.debugbear.com/basic-auth-header-generator

Should result in 200 OK with a response JSON.

**Comment by cmar7945** [comment]
Resolved, ended up resetting iDRAC to default for other reasons and it worked afterwards.
