### ISSUE TITLE
Wrong icon URL and missing attribution in device details.

### ISSUE THREAD

**Issue by psitem** [Breina/idrac_power_monitor#7]
![image](https://github.com/Breina/idrac_power_monitor/assets/5166927/cfdd6b02-d58c-429d-8050-5a00e0d5eef3)

The icon is pointing to: https://brands.home-assistant.io/idrac_power/icon.png (404)

Seems it should be: https://brands.home-assistant.io/idrac_power_monitor/icon.png

**Comment by Breina** [comment]
Thanks for noticing! Fix is underway... :)

**Comment by Breina** [comment]
Fixed :)

If you don't see it, do a CTRL + F5 to refresh your browser's cache.
