### ISSUE TITLE
Add into the readme the link for hacs

### ISSUE THREAD

**Issue by chicco-carone** [Breina/idrac_power_monitor#8]
I tried to install this integration from hacs but I couldn't find it. It would be useful to put the hacs link for the integration in the readme on GitHub.

**Comment by Breina** [comment]
Sorry, readme wasn't proactive in this one. You need to add it as a custom repository currently.

I've just submitted to HACS to become a default repository; could take a couple of days.

https://github.com/hacs/default/pull/2337

**Comment by chicco-carone** [comment]
> Sorry, readme wasn't proactive in this one. You need to add it as a custom repository currently.
> 
> I've just submitted to HACS to become a default repository; could take a couple of days.
> 
> https://github.com/hacs/default/pull/2337

Thanks for the reply I'll try it when it comes out on hacs

**Comment by chicco-carone** [comment]
> Sorry, readme wasn't proactive in this one. You need to add it as a custom repository currently.
> 
> I've just submitted to HACS to become a default repository; could take a couple of days.
> 
> https://github.com/hacs/default/pull/2337

Are there any updates on the hacs situation since I still can't find it .

**Comment by Breina** [comment]
Not yet, there's apparently a long backlog for the HACS guys.

If you want to use the integration right now, you can add this as a custom repository; https://hacs.xyz/docs/faq/custom_repositories/

**Comment by Breina** [comment]
As of 30/10, this is now in HACS. :)
