### ISSUE TITLE
Please add some extra features/info.

### ISSUE THREAD

**Issue by pbvdven** [Breina/idrac_power_monitor#9]
Hi, @Breina  

Thanks for this nice integration im using it a couple of months now and im really happy with it but i aso saw that someone made a fork of your project and added some extra options i tried that but had some issues refreshing the data and the development stopt its this one https://github.com/xmow49/idrac_server_monitor.

could you merge the extra options/info into your project that would be nice.

There is an issue with the one from xmow49 the integration stops refreshing the data after some time and after HA restart entities became unavailable ive u reconfigure the integration it started working again until it stops again.

Ive its not possible or to much work no problem thanks for looking at it. Ive i could do something to help just let me know.

![image](https://github.com/Breina/idrac_power_monitor/assets/39600990/597c9487-aeb8-46c9-a5ca-78199ecb577f)

**Comment by pbvdven** [comment]
Thanks that is quick. but i have the same issue with V1.2.0 that i had with his version its not renewing values your version does.

![image](https://github.com/Breina/idrac_power_monitor/assets/39600990/2ccb4950-f449-42b9-868d-8addabf7e2c3)

**Comment by Breina** [comment]
This version added an 'interval' option, defining how often it ought to update. Its default is every 300 seconds. When upgrading version, this default is applied to your config. If you want to alter it, please remove the config entry and re-add it, then you will see the 'interval' option so you can set it to whatever you want. :)

**Comment by pbvdven** [comment]
okay yes i know but that also isn't working as good with his version but i didn't try it yet in your V1.2.0.  i don't know how often your version refreshes the data if its push or pull? but yours worked better then how his version works for me your power measurements where more correct but all other things in his version are very nice.

**Comment by xmow49** [comment]
Thanks for this update.
I hadn't even noticed the problem with the update to HA 2024.2

I have a problem with the Power usage: there isn't any unit (W).

![image](https://github.com/Breina/idrac_power_monitor/assets/47485034/656ed6f8-3be8-4806-8011-bc36a4b0cb9f)

```
2024-02-12 21:33:11.034 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.poweredge_r730_power_usage (<class 'custom_components.idrac_power.sensor.IdracCurrentPowerSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power') it is using; expected one of ['W', 'kW']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/Breina/idrac_power_monitor/issues
```

and like @pbvdven says; yes I don't have any refresh after the init.

**Comment by Breina** [comment]
@xmow49 Pretty sure I fixed it. Now it works with callbacks.

One thing to note is that I don't bother updating the entities when the value stays the same. So you may be seeing larger intervals occasionally, but every `interval` at least, a new value is retrieved.

**Comment by xmow49** [comment]
@Breina Many Thanks; its working.
